//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OakStatisticalAnalysis {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Form1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Form1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OakStatisticalAnalysis.Form1", typeof(Form1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool basicRadioButton_AutoSize {
            get {
                object obj = ResourceManager.GetObject("basicRadioButton.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=308,Y=119}.
        /// </summary>
        public static System.Drawing.Point basicRadioButton_Location {
            get {
                object obj = ResourceManager.GetObject("basicRadioButton.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=72, Height=21}.
        /// </summary>
        public static System.Drawing.Size basicRadioButton_Size {
            get {
                object obj = ResourceManager.GetObject("basicRadioButton.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 6.
        /// </summary>
        public static int basicRadioButton_TabIndex {
            get {
                object obj = ResourceManager.GetObject("basicRadioButton.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to normal.
        /// </summary>
        public static string basicRadioButton_Text {
            get {
                return ResourceManager.GetString("basicRadioButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=199,Y=51}.
        /// </summary>
        public static System.Drawing.Point bootstrapBagsNumberTextBox_Location {
            get {
                object obj = ResourceManager.GetObject("bootstrapBagsNumberTextBox.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=44, Height=22}.
        /// </summary>
        public static System.Drawing.Size bootstrapBagsNumberTextBox_Size {
            get {
                object obj = ResourceManager.GetObject("bootstrapBagsNumberTextBox.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 7.
        /// </summary>
        public static int bootstrapBagsNumberTextBox_TabIndex {
            get {
                object obj = ResourceManager.GetObject("bootstrapBagsNumberTextBox.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string bootstrapBagsNumberTextBox_Text {
            get {
                return ResourceManager.GetString("bootstrapBagsNumberTextBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=199,Y=17}.
        /// </summary>
        public static System.Drawing.Point bootstrapPercentageTextBox_Location {
            get {
                object obj = ResourceManager.GetObject("bootstrapPercentageTextBox.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=44, Height=22}.
        /// </summary>
        public static System.Drawing.Size bootstrapPercentageTextBox_Size {
            get {
                object obj = ResourceManager.GetObject("bootstrapPercentageTextBox.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        public static int bootstrapPercentageTextBox_TabIndex {
            get {
                object obj = ResourceManager.GetObject("bootstrapPercentageTextBox.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,60.
        /// </summary>
        public static string bootstrapPercentageTextBox_Text {
            get {
                return ResourceManager.GetString("bootstrapPercentageTextBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool bootstrapRadioButton_AutoSize {
            get {
                object obj = ResourceManager.GetObject("bootstrapRadioButton.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode bootstrapRadioButton_ImeMode {
            get {
                object obj = ResourceManager.GetObject("bootstrapRadioButton.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=308,Y=142}.
        /// </summary>
        public static System.Drawing.Point bootstrapRadioButton_Location {
            get {
                object obj = ResourceManager.GetObject("bootstrapRadioButton.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=89, Height=21}.
        /// </summary>
        public static System.Drawing.Size bootstrapRadioButton_Size {
            get {
                object obj = ResourceManager.GetObject("bootstrapRadioButton.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 8.
        /// </summary>
        public static int bootstrapRadioButton_TabIndex {
            get {
                object obj = ResourceManager.GetObject("bootstrapRadioButton.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bootstrap.
        /// </summary>
        public static string bootstrapRadioButton_Text {
            get {
                return ResourceManager.GetString("bootstrapRadioButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode button1_ImeMode {
            get {
                object obj = ResourceManager.GetObject("button1.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=123}.
        /// </summary>
        public static System.Drawing.Point button1_Location {
            get {
                object obj = ResourceManager.GetObject("button1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=156, Height=23}.
        /// </summary>
        public static System.Drawing.Size button1_Size {
            get {
                object obj = ResourceManager.GetObject("button1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 4.
        /// </summary>
        public static int button1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("button1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BootstrapTrain.
        /// </summary>
        public static string button1_Text {
            get {
                return ResourceManager.GetString("button1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool corssvalidationRadioButton_AutoSize {
            get {
                object obj = ResourceManager.GetObject("corssvalidationRadioButton.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode corssvalidationRadioButton_ImeMode {
            get {
                object obj = ResourceManager.GetObject("corssvalidationRadioButton.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=308,Y=168}.
        /// </summary>
        public static System.Drawing.Point corssvalidationRadioButton_Location {
            get {
                object obj = ResourceManager.GetObject("corssvalidationRadioButton.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=116, Height=21}.
        /// </summary>
        public static System.Drawing.Size corssvalidationRadioButton_Size {
            get {
                object obj = ResourceManager.GetObject("corssvalidationRadioButton.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 7.
        /// </summary>
        public static int corssvalidationRadioButton_TabIndex {
            get {
                object obj = ResourceManager.GetObject("corssvalidationRadioButton.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crosvalidation.
        /// </summary>
        public static string corssvalidationRadioButton_Text {
            get {
                return ResourceManager.GetString("corssvalidationRadioButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=164,Y=46}.
        /// </summary>
        public static System.Drawing.Point crossvalidationNumOfPartsTextBox_Location {
            get {
                object obj = ResourceManager.GetObject("crossvalidationNumOfPartsTextBox.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=44, Height=22}.
        /// </summary>
        public static System.Drawing.Size crossvalidationNumOfPartsTextBox_Size {
            get {
                object obj = ResourceManager.GetObject("crossvalidationNumOfPartsTextBox.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 8.
        /// </summary>
        public static int crossvalidationNumOfPartsTextBox_TabIndex {
            get {
                object obj = ResourceManager.GetObject("crossvalidationNumOfPartsTextBox.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string crossvalidationNumOfPartsTextBox_Text {
            get {
                return ResourceManager.GetString("crossvalidationNumOfPartsTextBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=6,Y=51}.
        /// </summary>
        public static System.Drawing.Point ekstractFeaturesButton_Location {
            get {
                object obj = ResourceManager.GetObject("ekstractFeaturesButton.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=75, Height=23}.
        /// </summary>
        public static System.Drawing.Size ekstractFeaturesButton_Size {
            get {
                object obj = ResourceManager.GetObject("ekstractFeaturesButton.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        public static int ekstractFeaturesButton_TabIndex {
            get {
                object obj = ResourceManager.GetObject("ekstractFeaturesButton.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract.
        /// </summary>
        public static string ekstractFeaturesButton_Text {
            get {
                return ResourceManager.GetString("ekstractFeaturesButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode executeTestButton_ImeMode {
            get {
                object obj = ResourceManager.GetObject("executeTestButton.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=98,Y=94}.
        /// </summary>
        public static System.Drawing.Point executeTestButton_Location {
            get {
                object obj = ResourceManager.GetObject("executeTestButton.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=75, Height=23}.
        /// </summary>
        public static System.Drawing.Size executeTestButton_Size {
            get {
                object obj = ResourceManager.GetObject("executeTestButton.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 3.
        /// </summary>
        public static int executeTestButton_TabIndex {
            get {
                object obj = ResourceManager.GetObject("executeTestButton.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        public static string executeTestButton_Text {
            get {
                return ResourceManager.GetString("executeTestButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=88,Y=51}.
        /// </summary>
        public static System.Drawing.Point extractFeaturesSFSButton_Location {
            get {
                object obj = ResourceManager.GetObject("extractFeaturesSFSButton.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=105, Height=23}.
        /// </summary>
        public static System.Drawing.Size extractFeaturesSFSButton_Size {
            get {
                object obj = ResourceManager.GetObject("extractFeaturesSFSButton.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 4.
        /// </summary>
        public static int extractFeaturesSFSButton_TabIndex {
            get {
                object obj = ResourceManager.GetObject("extractFeaturesSFSButton.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract SFS.
        /// </summary>
        public static string extractFeaturesSFSButton_Text {
            get {
                return ResourceManager.GetString("extractFeaturesSFSButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool featureExtractionResultLabel_AutoSize {
            get {
                object obj = ResourceManager.GetObject("featureExtractionResultLabel.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=86}.
        /// </summary>
        public static System.Drawing.Point featureExtractionResultLabel_Location {
            get {
                object obj = ResourceManager.GetObject("featureExtractionResultLabel.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=56, Height=17}.
        /// </summary>
        public static System.Drawing.Size featureExtractionResultLabel_Size {
            get {
                object obj = ResourceManager.GetObject("featureExtractionResultLabel.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 3.
        /// </summary>
        public static int featureExtractionResultLabel_TabIndex {
            get {
                object obj = ResourceManager.GetObject("featureExtractionResultLabel.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result: .
        /// </summary>
        public static string featureExtractionResultLabel_Text {
            get {
                return ResourceManager.GetString("featureExtractionResultLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string featureNumberComboBox_Items {
            get {
                return ResourceManager.GetString("featureNumberComboBox.Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string featureNumberComboBox_Items1 {
            get {
                return ResourceManager.GetString("featureNumberComboBox.Items1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string featureNumberComboBox_Items2 {
            get {
                return ResourceManager.GetString("featureNumberComboBox.Items2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string featureNumberComboBox_Items3 {
            get {
                return ResourceManager.GetString("featureNumberComboBox.Items3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string featureNumberComboBox_Items4 {
            get {
                return ResourceManager.GetString("featureNumberComboBox.Items4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        public static string featureNumberComboBox_Items5 {
            get {
                return ResourceManager.GetString("featureNumberComboBox.Items5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        public static string featureNumberComboBox_Items6 {
            get {
                return ResourceManager.GetString("featureNumberComboBox.Items6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        public static string featureNumberComboBox_Items7 {
            get {
                return ResourceManager.GetString("featureNumberComboBox.Items7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=126,Y=17}.
        /// </summary>
        public static System.Drawing.Point featureNumberComboBox_Location {
            get {
                object obj = ResourceManager.GetObject("featureNumberComboBox.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=121, Height=24}.
        /// </summary>
        public static System.Drawing.Size featureNumberComboBox_Size {
            get {
                object obj = ResourceManager.GetObject("featureNumberComboBox.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        public static int featureNumberComboBox_TabIndex {
            get {
                object obj = ResourceManager.GetObject("featureNumberComboBox.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool featureNumberLabel_AutoSize {
            get {
                object obj = ResourceManager.GetObject("featureNumberLabel.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=20}.
        /// </summary>
        public static System.Drawing.Point featureNumberLabel_Location {
            get {
                object obj = ResourceManager.GetObject("featureNumberLabel.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=109, Height=17}.
        /// </summary>
        public static System.Drawing.Size featureNumberLabel_Size {
            get {
                object obj = ResourceManager.GetObject("featureNumberLabel.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        public static int featureNumberLabel_TabIndex {
            get {
                object obj = ResourceManager.GetObject("featureNumberLabel.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num of features.
        /// </summary>
        public static string featureNumberLabel_Text {
            get {
                return ResourceManager.GetString("featureNumberLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool label1_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label1.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode label1_ImeMode {
            get {
                object obj = ResourceManager.GetObject("label1.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=20}.
        /// </summary>
        public static System.Drawing.Point label1_Location {
            get {
                object obj = ResourceManager.GetObject("label1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=182, Height=17}.
        /// </summary>
        public static System.Drawing.Size label1_Size {
            get {
                object obj = ResourceManager.GetObject("label1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 5.
        /// </summary>
        public static int label1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent of training set used.
        /// </summary>
        public static string label1_Text {
            get {
                return ResourceManager.GetString("label1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool label2_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label2.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode label2_ImeMode {
            get {
                object obj = ResourceManager.GetObject("label2.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=51}.
        /// </summary>
        public static System.Drawing.Point label2_Location {
            get {
                object obj = ResourceManager.GetObject("label2.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=148, Height=17}.
        /// </summary>
        public static System.Drawing.Size label2_Size {
            get {
                object obj = ResourceManager.GetObject("label2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 6.
        /// </summary>
        public static int label2_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label2.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num of boostrap bags.
        /// </summary>
        public static string label2_Text {
            get {
                return ResourceManager.GetString("label2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool label3_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label3.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode label3_ImeMode {
            get {
                object obj = ResourceManager.GetObject("label3.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=13,Y=33}.
        /// </summary>
        public static System.Drawing.Point label3_Location {
            get {
                object obj = ResourceManager.GetObject("label3.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=138, Height=17}.
        /// </summary>
        public static System.Drawing.Size label3_Size {
            get {
                object obj = ResourceManager.GetObject("label3.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 5.
        /// </summary>
        public static int label3_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label3.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part of train/test split.
        /// </summary>
        public static string label3_Text {
            get {
                return ResourceManager.GetString("label3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool label4_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label4.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode label4_ImeMode {
            get {
                object obj = ResourceManager.GetObject("label4.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=13,Y=46}.
        /// </summary>
        public static System.Drawing.Point label4_Location {
            get {
                object obj = ResourceManager.GetObject("label4.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=89, Height=17}.
        /// </summary>
        public static System.Drawing.Size label4_Size {
            get {
                object obj = ResourceManager.GetObject("label4.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 8.
        /// </summary>
        public static int label4_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label4.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num of parts.
        /// </summary>
        public static string label4_Text {
            get {
                return ResourceManager.GetString("label4.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool label5_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label5.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode label5_ImeMode {
            get {
                object obj = ResourceManager.GetObject("label5.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=207,Y=33}.
        /// </summary>
        public static System.Drawing.Point label5_Location {
            get {
                object obj = ResourceManager.GetObject("label5.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=20, Height=17}.
        /// </summary>
        public static System.Drawing.Size label5_Size {
            get {
                object obj = ResourceManager.GetObject("label5.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 6.
        /// </summary>
        public static int label5_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label5.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        public static string label5_Text {
            get {
                return ResourceManager.GetString("label5.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool label6_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label6.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode label6_ImeMode {
            get {
                object obj = ResourceManager.GetObject("label6.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=14,Y=63}.
        /// </summary>
        public static System.Drawing.Point label6_Location {
            get {
                object obj = ResourceManager.GetObject("label6.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=84, Height=17}.
        /// </summary>
        public static System.Drawing.Size label6_Size {
            get {
                object obj = ResourceManager.GetObject("label6.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 7.
        /// </summary>
        public static int label6_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label6.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classificator
        ///.
        /// </summary>
        public static string label6_Text {
            get {
                return ResourceManager.GetString("label6.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool label7_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label7.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode label7_ImeMode {
            get {
                object obj = ResourceManager.GetObject("label7.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=13,Y=16}.
        /// </summary>
        public static System.Drawing.Point label7_Location {
            get {
                object obj = ResourceManager.GetObject("label7.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=42, Height=17}.
        /// </summary>
        public static System.Drawing.Size label7_Size {
            get {
                object obj = ResourceManager.GetObject("label7.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 8.
        /// </summary>
        public static int label7_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label7.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        public static string label7_Text {
            get {
                return ResourceManager.GetString("label7.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool label8_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label8.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode label8_ImeMode {
            get {
                object obj = ResourceManager.GetObject("label8.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=13,Y=15}.
        /// </summary>
        public static System.Drawing.Point label8_Location {
            get {
                object obj = ResourceManager.GetObject("label8.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=106, Height=17}.
        /// </summary>
        public static System.Drawing.Size label8_Size {
            get {
                object obj = ResourceManager.GetObject("label8.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 9.
        /// </summary>
        public static int label8_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label8.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrossValidation.
        /// </summary>
        public static string label8_Text {
            get {
                return ResourceManager.GetString("label8.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool label9_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label9.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode label9_ImeMode {
            get {
                object obj = ResourceManager.GetObject("label9.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=3}.
        /// </summary>
        public static System.Drawing.Point label9_Location {
            get {
                object obj = ResourceManager.GetObject("label9.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=69, Height=17}.
        /// </summary>
        public static System.Drawing.Size label9_Size {
            get {
                object obj = ResourceManager.GetObject("label9.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 10.
        /// </summary>
        public static int label9_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label9.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootstrap.
        /// </summary>
        public static string label9_Text {
            get {
                return ResourceManager.GetString("label9.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=0}.
        /// </summary>
        public static System.Drawing.Point menuStrip2_Location {
            get {
                object obj = ResourceManager.GetObject("menuStrip2.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=700, Height=28}.
        /// </summary>
        public static System.Drawing.Size menuStrip2_Size {
            get {
                object obj = ResourceManager.GetObject("menuStrip2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        public static int menuStrip2_TabIndex {
            get {
                object obj = ResourceManager.GetObject("menuStrip2.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menuStrip2.
        /// </summary>
        public static string menuStrip2_Text {
            get {
                return ResourceManager.GetString("menuStrip2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=17}.
        /// </summary>
        public static System.Drawing.Point menuStrip2_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuStrip2.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=12,Y=46}.
        /// </summary>
        public static System.Drawing.Point panel1_Location {
            get {
                object obj = ResourceManager.GetObject("panel1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=264, Height=113}.
        /// </summary>
        public static System.Drawing.Size panel1_Size {
            get {
                object obj = ResourceManager.GetObject("panel1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        public static int panel1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("panel1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=18,Y=190}.
        /// </summary>
        public static System.Drawing.Point panel2_Location {
            get {
                object obj = ResourceManager.GetObject("panel2.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=258, Height=185}.
        /// </summary>
        public static System.Drawing.Size panel2_Size {
            get {
                object obj = ResourceManager.GetObject("panel2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        public static int panel2_TabIndex {
            get {
                object obj = ResourceManager.GetObject("panel2.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=430,Y=53}.
        /// </summary>
        public static System.Drawing.Point panel3_Location {
            get {
                object obj = ResourceManager.GetObject("panel3.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=258, Height=116}.
        /// </summary>
        public static System.Drawing.Size panel3_Size {
            get {
                object obj = ResourceManager.GetObject("panel3.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 4.
        /// </summary>
        public static int panel3_TabIndex {
            get {
                object obj = ResourceManager.GetObject("panel3.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=430,Y=175}.
        /// </summary>
        public static System.Drawing.Point panel4_Location {
            get {
                object obj = ResourceManager.GetObject("panel4.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=258, Height=116}.
        /// </summary>
        public static System.Drawing.Size panel4_Size {
            get {
                object obj = ResourceManager.GetObject("panel4.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 5.
        /// </summary>
        public static int panel4_TabIndex {
            get {
                object obj = ResourceManager.GetObject("panel4.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=430,Y=297}.
        /// </summary>
        public static System.Drawing.Point panel5_Location {
            get {
                object obj = ResourceManager.GetObject("panel5.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=258, Height=98}.
        /// </summary>
        public static System.Drawing.Size panel5_Size {
            get {
                object obj = ResourceManager.GetObject("panel5.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 9.
        /// </summary>
        public static int panel5_TabIndex {
            get {
                object obj = ResourceManager.GetObject("panel5.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=122, Height=24}.
        /// </summary>
        public static System.Drawing.Size readDatabaseToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("readDatabaseToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Database.
        /// </summary>
        public static string readDatabaseToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("readDatabaseToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=143, Height=26}.
        /// </summary>
        public static System.Drawing.Size readFromFile_Size {
            get {
                object obj = ResourceManager.GetObject("readFromFile.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From file.
        /// </summary>
        public static string readFromFile_Text {
            get {
                return ResourceManager.GetString("readFromFile.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NN.
        /// </summary>
        public static string selectClassifierComboBox_Items {
            get {
                return ResourceManager.GetString("selectClassifierComboBox.Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NM.
        /// </summary>
        public static string selectClassifierComboBox_Items1 {
            get {
                return ResourceManager.GetString("selectClassifierComboBox.Items1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kNN.
        /// </summary>
        public static string selectClassifierComboBox_Items2 {
            get {
                return ResourceManager.GetString("selectClassifierComboBox.Items2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kNM.
        /// </summary>
        public static string selectClassifierComboBox_Items3 {
            get {
                return ResourceManager.GetString("selectClassifierComboBox.Items3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=120,Y=56}.
        /// </summary>
        public static System.Drawing.Point selectClassifierComboBox_Location {
            get {
                object obj = ResourceManager.GetObject("selectClassifierComboBox.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=82, Height=24}.
        /// </summary>
        public static System.Drawing.Size selectClassifierComboBox_Size {
            get {
                object obj = ResourceManager.GetObject("selectClassifierComboBox.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        public static int selectClassifierComboBox_TabIndex {
            get {
                object obj = ResourceManager.GetObject("selectClassifierComboBox.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text|*.txt;.
        /// </summary>
        public static string selectDatabaseFileDialog_Filter {
            get {
                return ResourceManager.GetString("selectDatabaseFileDialog.Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=132,Y=17}.
        /// </summary>
        public static System.Drawing.Point selectDatabaseFileDialog_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("selectDatabaseFileDialog.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OakStatisticalAnalisysisForm.
        /// </summary>
        public static string this_Name {
            get {
                return ResourceManager.GetString("this.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string this_Text {
            get {
                return ResourceManager.GetString("this.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=94}.
        /// </summary>
        public static System.Drawing.Point trainButton_Location {
            get {
                object obj = ResourceManager.GetObject("trainButton.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=75, Height=23}.
        /// </summary>
        public static System.Drawing.Size trainButton_Size {
            get {
                object obj = ResourceManager.GetObject("trainButton.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        public static int trainButton_TabIndex {
            get {
                object obj = ResourceManager.GetObject("trainButton.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train.
        /// </summary>
        public static string trainButton_Text {
            get {
                return ResourceManager.GetString("trainButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=157,Y=30}.
        /// </summary>
        public static System.Drawing.Point trainTestRatioTextBox_Location {
            get {
                object obj = ResourceManager.GetObject("trainTestRatioTextBox.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=44, Height=22}.
        /// </summary>
        public static System.Drawing.Size trainTestRatioTextBox_Size {
            get {
                object obj = ResourceManager.GetObject("trainTestRatioTextBox.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        public static int trainTestRatioTextBox_TabIndex {
            get {
                object obj = ResourceManager.GetObject("trainTestRatioTextBox.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,80.
        /// </summary>
        public static string trainTestRatioTextBox_Text {
            get {
                return ResourceManager.GetString("trainTestRatioTextBox.Text", resourceCulture);
            }
        }
    }
}
